// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uhk.vanouzu1.model;

import io.springlets.format.EntityFormat;
import uhk.vanouzu1.model.MistnostFormBean;

privileged aspect MistnostFormBean_Roo_DTO {
    
    declare @type: MistnostFormBean: @EntityFormat;
    
}
